### ISSUE TITLE
Wicket 7 support

### ISSUE THREAD

**Issue by jchappelle** [decebals/wicket-plugin#2]
Hi,

We use wicket 7 and I'm starting to try and integrate your plugin framework. My first step is to use ExtensionPoints without making it an actual plugin. I noticed the transitive dependencies on wicket 6.8. I'm going to try and exclude those in my maven pom and see if it still works. 

Any plan of when you will have a version for wicket 7?

**Comment by jchappelle** [comment]
Just some further information. I don't think you need to do anything. I pulled in the wicket-plugin project and changed the version to 7.1.0. The code compiled. I got a runtime exception because of the jetty plugin using servlet api 2.5, I switched the a new version and the demo ran like a charm. 

For now I'll just exclude those transitive dependencies. I expect everything to work in Wicket 7.1. I'll let you know if I find otherwise.

**Comment by decebals** [comment]
@jchappelle I updated Wicket to 7.2.0 and PF4J to 0.12.0
If everything is OK I can release a new version tomorrow.

**Comment by jchappelle** [comment]
Great! I'm hitting some strange errors that look to be jar compatibility. Just to keep moving I'm going to pull the source in and update it. Tomorrow I'll grab your new release.

Thanks!
