### ISSUE TITLE
Error while instantiating a Plugin

### ISSUE THREAD

**Issue by mursch** [decebals/wicket-plugin#8]
I'm actually trying to make an existing wicket application extensible. Therefore I integrated wicket-plugin, wrote a first tiny plugin (only a static panel) and tried to add it to a page as shown in the demo app. 
At startup the framework recognizes the plugin but wenn the plugin class is instantiated (in the class DefaultExtensionFactory) an Exception is thrown: 

<pre>
org.apache.wicket.WicketRuntimeException: There is no application attached to current thread http-nio-8081-exec-9
	at org.apache.wicket.Application.get(Application.java:236)
	at org.apache.wicket.Component.getApplication(Component.java:1350)
	at org.apache.wicket.Component.<init>(Component.java:687)
	at org.apache.wicket.MarkupContainer.<init>(MarkupContainer.java:180)
	at org.apache.wicket.markup.html.WebMarkupContainer.<init>(WebMarkupContainer.java:53)
	at org.apache.wicket.markup.html.WebMarkupContainer.<init>(WebMarkupContainer.java:45)
	at org.apache.wicket.markup.html.panel.Panel.<init>(Panel.java:67)
</pre>

Do you know what went wrong or what might be the reason for this error?

I start the application from eclipse with -Dpf4j.mode=development

**Comment by decebals** [comment]
What wicket version you use in your application? The error is from wicket, you call getApplication method but you are not in a request-response cycle. Can you show more from the error stack trace?

**Comment by decebals** [comment]
Can you run the demo (it's in demo directory) ?

I tried and it seems to work:
![image](https://user-images.githubusercontent.com/1248311/36786615-b7a3ff50-1c8f-11e8-8e94-eca1c32b5c83.png)
![image](https://user-images.githubusercontent.com/1248311/36786687-fae2235a-1c8f-11e8-967e-0dbe17d8d00c.png)
![image](https://user-images.githubusercontent.com/1248311/36786635-cfa0cf3e-1c8f-11e8-9a10-70f507878b11.png)

**Comment by decebals** [comment]
An d by the way:
> Application.get is called during the initialisation of the plugin class.

You cannot call `Application#get` from your `Plugin#start` or in the constructor. Application#get is callable only in a context of the web layer (Wicket) when you have an HTTP request from client (browser).

**Comment by martin-g** [comment]
Or you may use `Application#get(String)` to get it by name even in non-http request **but** after Wicket#init() is executed.

**Comment by decebals** [comment]
Martin is the master on Wicket :)
Martin, it's a pleasure to see a comment from you on this project :smile: I appreciate very much your contribution to open source in general and to Wicket in particular.
I have not used Wicket anymore in the past two years but I think that it's still an excellent web framework.

I am happy to see that people use this library. I will try to update it.

**Comment by mursch** [comment]
First of all: thank you for the quick response!
I think I have to review my codebase again - something is wrong with my integration of wicket-plugin. 
It's still not working. When I find a solution to my problem I let you know!

**Comment by decebals** [comment]
@mursch 
If you could share some code with us, we can help you.
My advice is to start with demo project and add incrementally, step by step, your business.

By the way, I started to update this project to PF4J 2.x.
PF4J 2.x is more friendly and come out of the box with support for JAR as plugin (simplify plugin package process).

**Comment by mursch** [comment]
Yesterday I had a very similar idea: I integrated the demo into my project structure and .... it works! :)

I also upgraded to version 0.6.0.SNAPSHOT. When do you plan to make a new release?

**Comment by decebals** [comment]
@mursch Congratulations :+1:.
Version 1.0.0 will be released in few days (I think). The next version will come with support for last PF4J version, a simplified demo (switched from ZIP to JAR as plugin storage), new package root (org.pf4j.wicket instead og ro.fortsoft.wicket.plugin).

**Comment by mursch** [comment]
Cool 👍  I will upgrade to Version 1 as soon as it is out. Great work!

**Comment by decebals** [comment]
> Version 1.0.0 will be released in few days (I think)

Sorry for delay. I am very busy these days.

**Comment by mursch** [comment]
I'm looking forward to the new version!
I close this issue because obviously I did something wrong in my first attempts integrating wicket-plugin.

**Comment by decebals** [comment]
@mursch 
Version `1.0.0` is fresh :smile:. Please try to use it and if you encounter problems create issue(s).

**Comment by mursch** [comment]
Great news - thank you! I'll update to 1.0.0 in the course of this week.
