### ISSUE TITLE
Spring integration

### ISSUE THREAD

**Issue by mursch** [decebals/wicket-plugin#9]
This is more of a question:
Is it possible to configure spring managed beans inside a wicket plugin?  A plugin may need additional service/repository classes or even additional database tables with related mapping classes.

The pf4j projects includes a spring integrations, but you have to extend your plugin class from SpringPlugin (however, a wicket plugin has to be extended from WicketPlugin to be noticed by the plugin manager).

Is there a way to achieve spring integration within a wicket plugin?

**Comment by decebals** [comment]
Wicket-plugin doesn't come with a special requirements related to PluginManager.
You can use SpringPluginManager. 
Take a look at:
- https://github.com/decebals/wicket-plugin/blob/master/demo/app/src/main/java/ro/fortsoft/wicket/plugin/demo/WicketApplication.java#L59
 - https://github.com/decebals/wicket-plugin/blob/master/wicket-plugin/src/main/java/ro/fortsoft/wicket/plugin/PluginManagerInitializer.java#L103

**Comment by mursch** [comment]
Thanks for the hint. In the meantime i managed to integrate Spring. I used the pf4j.spring project as an inspiration.
